name: Test parameters JSON meta schema

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema-version: [0.1.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install ajv-cli 5.0.0
        run: npm install -g ajv-cli@5.0.0
      - name: Test valid JSON schemas (${{ matrix.schema-version }})
        run: ajv test -s parameters/${{ matrix.schema-version}}/schema.json -d parameters/${{ matrix.schema-version }}/tests/*.json --spec=draft2020 --validate-formats=false --valid

