name: Validate JSONs

on: [pull_request]

# https://github.com/OrRosenblatt/validate-json-action?tab=readme-ov-file#example-workflow
jobs:
  parameters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: parameters/0.1.0/schema.json
          INPUT_JSONS: parameters/0.1.0/tests/*.json